apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: app
data:
  # Configurações do Banco de Dados (DB_HOST aponta para o Service do Postgres no outro Namespace)
  DB_HOST: "postgres-service.db-students.svc.cluster.local" # FQDN do Service
  DB_PORT: "5432"
  DB_NAME: "messagesdb"
  # Configurações do Flask API
  API_HOST: "0.0.0.0" # O host interno do container
  API_PORT: "5000"    # A porta do Flask
