apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: students-ingress
  namespace: app 
  annotations:
    # 1. REMOVER A ANOTAÇÃO DE REWRITE:
    # nginx.ingress.kubernetes.io/rewrite-target: /$1
    networking.kubernetes.io/ingress.class: "nginx"

spec:
  ingressClassName: nginx 
  rules:
  - http:
      paths:
      # Rota para o Backend: Mantém o '/api' no path enviado ao Backend
      - path: /api
        pathType: Prefix
        backend:
          service:
            name: backend-service
            port:
              number: 5000
      # Rota para o Frontend
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend-service
            port:
              number: 80
